# Generated by Django 3.0.8 on 2020-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200825_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=' ', upload_to='category_images/'),
        ),
    ]
