# Generated by Django 3.0.8 on 2020-12-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_items_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default=' ', upload_to='item_images/'),
        ),
    ]
