# Generated by Django 3.0.8 on 2020-12-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Category'),
        ),
    ]
