# Generated by Django 3.0.8 on 2020-12-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20201205_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
