# Generated by Django 3.0.8 on 2020-12-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_delete_pricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
